version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: JEE
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  springapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    networks:
      - backend-network
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - springapp
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
    driver: bridge